repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
    files: '\.(js|css|py|ya?ml|json|md|toml|ini)$'
  - id: check-docstring-first
  - id: check-symlinks
  - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
